# Generated by Django 2.0 on 2019-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_inherit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inheritpageplaceholder',
            name='from_language',
            field=models.CharField(blank=True, choices=[('en', 'en'), ('ar', 'ar')], help_text='Optional: the language of the plugins you want', max_length=5, null=True, verbose_name='language'),
        ),
    ]
