# Generated by Django 2.0 on 2019-06-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_inherit', '0002_auto_20190612_1659'),
        ('djangocms_inherit', '0003_auto_20160825_1821'),
    ]

    operations = [
    ]
